version: "3"
services:
  user-service:
    container_name: user-service
    build: ./user-service
    image: user-image
    ports:
      - "8081:8081"
    depends_on:
      - postDB
      - eureka

  account-service:
    container_name: account-service
    build: ./account-service
    image: account-image
    ports:
      - "8082:8082"
    depends_on:
      - mongoDB
      - eureka

  api-gateway:
    container_name: api-gateway
    build: ./api-gateway
    image: api-image
    ports:
      - "8080:8080"
    depends_on:
      - eureka

  eureka:
    container_name: eureka
    image: eureka-image
    build: ./discovery-server
    ports:
      - "8761:8761"

  postDB:
    container_name: postgresDB
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=user
      - POSTGRES_DB=bank

  mongoDB:
    container_name: mongoDB
    image: mongo:4.0.1
    ports:
      - "27017:27017"
